-   id: markdownlint
    name: markdownlint
    description: "Checks the style of Markdown/Commonmark files."
    entry: markdownlint
    language: node
    types: [markdown]
    minimum_pre_commit_version: 0.15.0
-   id: markdownlint-fix
    name: markdownlint-fix
    description: "Fixes the style of Markdown/Commonmark files."
    entry: markdownlint --fix
    language: node
    types: [markdown]
    minimum_pre_commit_version: 0.15.0
-   id: markdownlint-docker
    name: markdownlint-docker
    description: "Checks the style of Markdown/Commonmark files."
    entry: ghcr.io/igorshubovych/markdownlint-cli
    language: docker_image
    types: [markdown]
    minimum_pre_commit_version: 0.15.0
-   id: markdownlint-fix-docker
    name: markdownlint-fix-docker
    description: "Fixes the style of Markdown/Commonmark files."
    entry: ghcr.io/igorshubovych/markdownlint-cli --fix
    language: docker_image
    types: [markdown]
    minimum_pre_commit_version: 0.15.0
